# Generated by Django 5.2.5 on 2025-08-30 18:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('device_id', models.CharField(max_length=255, unique=True)),
                ('device_name', models.CharField(max_length=255)),
                ('device_type', models.CharField(max_length=50)),
                ('device_model', models.CharField(blank=True, max_length=255)),
                ('push_token', models.TextField(blank=True)),
                ('push_enabled', models.BooleanField(default=False)),
                ('is_trusted', models.BooleanField(default=False)),
                ('trusted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_devices',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('refresh_token_hash', models.CharField(max_length=128)),
                ('refresh_token_family', models.CharField(max_length=64)),
                ('rotation_counter', models.IntegerField(default=0)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoke_reason', models.CharField(blank=True, max_length=50)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_sessions.device')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_sessions',
            },
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['user', '-last_seen_at'], name='user_device_user_id_2fc9bc_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['device_id'], name='user_device_device__945e98_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['user', '-created_at'], name='user_sessio_user_id_35bce9_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['refresh_token_family'], name='user_sessio_refresh_90d2e5_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['revoked_at'], name='user_sessio_revoked_759f1e_idx'),
        ),
    ]
