version: 2
updates:
  - package-ecosystem: pip
    directory: /authstack
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: /Ontime_ethiopia_flutterapp
    schedule:
      interval: weekly
