# Generated by Django 5.2.5 on 2025-08-30 18:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('otp_type', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone')], max_length=10)),
                ('destination', models.CharField(db_index=True, max_length=255)),
                ('otp_code', models.CharField(max_length=6)),
                ('otp_hash', models.CharField(max_length=128)),
                ('purpose', models.CharField(choices=[('login', 'Login'), ('register', 'Registration'), ('verify', 'Verification'), ('reset', 'Password Reset')], max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('attempts', models.IntegerField(default=0)),
                ('max_attempts', models.IntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'otp_requests',
                'indexes': [models.Index(fields=['destination', '-created_at'], name='otp_request_destina_6a886a_idx'), models.Index(fields=['otp_code', 'destination'], name='otp_request_otp_cod_5a560d_idx')],
            },
        ),
    ]
