# Generated by Django 5.2.5 on 2025-08-30 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprequest',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='otprequest',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
