# Generated by Django 5.2.5 on 2025-10-10 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channels', '0005_playlist_video_alter_featureflag_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Live',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant', models.CharField(db_index=True, help_text='Tenant slug (e.g., ontime)', max_length=64)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('poster_url', models.URLField(blank=True, default='')),
                ('playback_url', models.CharField(help_text='HLS/DASH URL', max_length=1024)),
                ('playback_type', models.CharField(choices=[('hls', 'HLS (.m3u8)'), ('dash', 'MPEG-DASH (.mpd)')], default='hls', max_length=8)),
                ('drm', models.JSONField(blank=True, default=dict, help_text='Optional DRM config: {widevine: {license_url: ...}, fairplay: {...}}')),
                ('is_active', models.BooleanField(default=True)),
                ('is_previewable', models.BooleanField(default=True, help_text='Allow admin preview in Django')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='live', to='channels.channel')),
            ],
            options={
                'verbose_name': 'Live',
                'verbose_name_plural': 'Live',
                'ordering': ['-updated_at', 'channel__sort_order'],
            },
        ),
        migrations.CreateModel(
            name='LiveSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('live', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='live.live')),
            ],
            options={
                'verbose_name': 'Live schedule',
                'verbose_name_plural': 'Live schedules',
                'ordering': ['start_at'],
            },
        ),
    ]
