# Generated by Django 5.2.5 on 2025-11-06 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0012_shortcomment_shortreaction'),
        ('live', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='live',
            name='access_token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='live',
            name='ad_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='live',
            name='added_by',
            field=models.ForeignKey(blank=True, help_text='Which admin or user created the entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_added', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='live',
            name='aspect_ratio',
            field=models.CharField(blank=True, default='', help_text='e.g., 16:9', max_length=16),
        ),
        migrations.AddField(
            model_name='live',
            name='backup_stream_url',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='live',
            name='banner_image',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='live',
            name='bitrate',
            field=models.IntegerField(blank=True, help_text='kbps', null=True),
        ),
        migrations.AddField(
            model_name='live',
            name='category',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='live',
            name='city',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='live',
            name='country',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='live',
            name='current_program',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='live',
            name='epg_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='live',
            name='facebook_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='live',
            name='has_epg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='live',
            name='instagram_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='live',
            name='is_free',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='live',
            name='is_local',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='live',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='live',
            name='language',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='live',
            name='license_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='live',
            name='listener_count',
            field=models.IntegerField(default=0, help_text='Current or last known listeners (if applicable)'),
        ),
        migrations.AddField(
            model_name='live',
            name='logo',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='live',
            name='next_program',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='live',
            name='payment_provider',
            field=models.CharField(blank=True, default='', help_text='Chapa, Telebirr, Stripe, etc.', max_length=32),
        ),
        migrations.AddField(
            model_name='live',
            name='price_per_month',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='live',
            name='priority',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='live',
            name='region_lock',
            field=models.JSONField(blank=True, default=list, help_text='List of allowed countries or codes'),
        ),
        migrations.AddField(
            model_name='live',
            name='requires_login',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='live',
            name='requires_vpn',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='live',
            name='resolution',
            field=models.CharField(blank=True, default='', help_text='e.g., 720p, 1080p', max_length=16),
        ),
        migrations.AddField(
            model_name='live',
            name='schedule_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='live',
            name='stream_health',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='live',
            name='stream_type',
            field=models.CharField(blank=True, default='', help_text='HLS, DASH, RTMP, YouTube Live, IPTV, etc.', max_length=32),
        ),
        migrations.AddField(
            model_name='live',
            name='stream_url',
            field=models.CharField(blank=True, default='', help_text='Main live stream URL (alias of playback_url)', max_length=1024),
        ),
        migrations.AddField(
            model_name='live',
            name='thumbnail_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='live',
            name='total_listens',
            field=models.BigIntegerField(default=0, help_text='Total play count (if applicable)'),
        ),
        migrations.AddField(
            model_name='live',
            name='total_views',
            field=models.BigIntegerField(default=0, help_text='Cumulative view count'),
        ),
        migrations.AddField(
            model_name='live',
            name='twitter_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='live',
            name='viewer_count',
            field=models.IntegerField(default=0, help_text='Current live viewers'),
        ),
        migrations.AddField(
            model_name='live',
            name='website_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='live',
            name='youtube_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='LiveRadio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant', models.CharField(db_index=True, help_text='Tenant slug (e.g., ontime)', max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('language', models.CharField(blank=True, default='', max_length=32)),
                ('country', models.CharField(blank=True, default='', max_length=64)),
                ('city', models.CharField(blank=True, default='', max_length=64)),
                ('category', models.CharField(blank=True, default='', max_length=64)),
                ('stream_url', models.CharField(max_length=1024)),
                ('backup_stream_url', models.CharField(blank=True, default='', max_length=1024)),
                ('bitrate', models.IntegerField(blank=True, null=True)),
                ('format', models.CharField(blank=True, default='', help_text='HLS, AAC, MP3, RTMP, etc.', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('logo', models.URLField(blank=True, default='')),
                ('banner_image', models.URLField(blank=True, default='')),
                ('website_url', models.URLField(blank=True, default='')),
                ('facebook_url', models.URLField(blank=True, default='')),
                ('twitter_url', models.URLField(blank=True, default='')),
                ('instagram_url', models.URLField(blank=True, default='')),
                ('is_free', models.BooleanField(default=True)),
                ('price_per_month', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('requires_login', models.BooleanField(default=False)),
                ('payment_provider', models.CharField(blank=True, default='', max_length=32)),
                ('access_token_expiry', models.DateTimeField(blank=True, null=True)),
                ('listener_count', models.IntegerField(default=0, help_text='Current or last known listeners')),
                ('total_listens', models.BigIntegerField(default=0, help_text='Total play count')),
                ('priority', models.IntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, help_text='Which admin or user created the entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='radio_added', to=settings.AUTH_USER_MODEL)),
                ('channel', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='radio', to='channels.channel')),
            ],
            options={
                'verbose_name': 'Live radio',
                'verbose_name_plural': 'Live radios',
                'ordering': ['-updated_at', 'priority', 'name'],
            },
        ),
    ]
