# Generated by Django 5.2.5 on 2025-11-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0002_live_access_token_expiry_live_ad_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveradio',
            name='last_check_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='liveradio',
            name='last_check_ok',
            field=models.BooleanField(default=False, help_text='Whether the last health check succeeded'),
        ),
        migrations.AddField(
            model_name='liveradio',
            name='last_error',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
