# Generated by Django 5.2.5 on 2025-09-07 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channels', '0005_playlist_video_alter_featureflag_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant', models.CharField(db_index=True, default='ontime', max_length=64)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('synopsis', models.TextField(blank=True, default='')),
                ('cover_image', models.URLField(blank=True, null=True)),
                ('default_locale', models.CharField(default='am', max_length=8)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shows', to='channels.channel')),
            ],
            options={
                'ordering': ['title', 'slug'],
                'permissions': (('manage_content', 'Can manage series content'),),
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant', models.CharField(db_index=True, default='ontime', max_length=64)),
                ('number', models.IntegerField()),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('cover_image', models.URLField(blank=True, null=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('yt_playlist_id', models.CharField(help_text='YouTube playlist ID (PL...)', max_length=64)),
                ('include_rules', models.JSONField(blank=True, default=list)),
                ('exclude_rules', models.JSONField(blank=True, default=list)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='series.show')),
            ],
            options={
                'ordering': ['show', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant', models.CharField(db_index=True, default='ontime', max_length=64)),
                ('source_video_id', models.CharField(db_index=True, max_length=32)),
                ('source_published_at', models.DateTimeField(blank=True, null=True)),
                ('episode_number', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('thumbnails', models.JSONField(blank=True, default=dict)),
                ('title_override', models.CharField(blank=True, default='', max_length=255)),
                ('description_override', models.TextField(blank=True, default='')),
                ('publish_at', models.DateTimeField(blank=True, null=True)),
                ('visible', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('published', 'Published'), ('draft', 'Draft'), ('needs_review', 'Needs Review')], default='published', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='series.season')),
            ],
            options={
                'ordering': ['season', 'episode_number', 'source_published_at', 'id'],
                'indexes': [models.Index(fields=['tenant', 'season', 'episode_number'], name='series_epis_tenant_1b9927_idx'), models.Index(fields=['tenant', 'season', 'source_video_id'], name='series_epis_tenant_11ddaf_idx'), models.Index(fields=['tenant', 'status', 'visible'], name='series_epis_tenant_bb9b9f_idx')],
                'unique_together': {('season', 'source_video_id')},
            },
        ),
        migrations.AddIndex(
            model_name='show',
            index=models.Index(fields=['tenant', 'slug'], name='series_show_tenant_e03a95_idx'),
        ),
        migrations.AddIndex(
            model_name='show',
            index=models.Index(fields=['tenant', 'is_active'], name='series_show_tenant_86dcad_idx'),
        ),
        migrations.AddIndex(
            model_name='season',
            index=models.Index(fields=['tenant', 'show', 'number'], name='series_seas_tenant_0e29de_idx'),
        ),
        migrations.AddIndex(
            model_name='season',
            index=models.Index(fields=['tenant', 'yt_playlist_id'], name='series_seas_tenant_2a08f9_idx'),
        ),
        migrations.AddIndex(
            model_name='season',
            index=models.Index(fields=['tenant', 'is_enabled'], name='series_seas_tenant_910098_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='season',
            unique_together={('show', 'number')},
        ),
    ]
