# Generated by Django 5.2.5 on 2025-09-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='cover_upload',
            field=models.ImageField(blank=True, null=True, upload_to='series/covers/seasons/'),
        ),
        migrations.AddField(
            model_name='show',
            name='cover_upload',
            field=models.ImageField(blank=True, null=True, upload_to='series/covers/shows/'),
        ),
    ]
