# Generated by Django 5.2.5 on 2025-11-04 13:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0003_episodeview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant', models.CharField(db_index=True, default='ontime', max_length=64)),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=128)),
                ('color', models.CharField(blank=True, help_text='Hex color (#RRGGBB or #RRGGBBAA)', max_length=9, validators=[django.core.validators.RegexValidator(message='Color must be a hex value like #RRGGBB or #RRGGBBAA', regex='^#([0-9A-Fa-f]{6}|[0-9A-Fa-f]{8})$')])),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['tenant', 'slug'], name='series_cate_tenant_163fbc_idx'), models.Index(fields=['tenant', 'is_active'], name='series_cate_tenant_9ae1d7_idx')],
                'unique_together': {('tenant', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='show',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='shows', to='series.category'),
        ),
    ]
