# Generated by Django 5.2.5 on 2025-08-29 19:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tenant', models.CharField(db_index=True, default='ontime', max_length=64)),
                ('id_slug', models.SlugField(max_length=128, unique=True)),
                ('default_locale', models.CharField(choices=[('am', 'Amharic'), ('en', 'English')], default='am', max_length=8)),
                ('name_am', models.CharField(blank=True, max_length=255, null=True)),
                ('name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('images', models.JSONField(blank=True, default=list)),
                ('sources', models.JSONField(blank=True, default=list)),
                ('genres', models.JSONField(blank=True, default=list)),
                ('language', models.CharField(default='am', max_length=8)),
                ('country', models.CharField(default='ET', max_length=2)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('platforms', models.JSONField(blank=True, default=list)),
                ('drm_required', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=100)),
                ('featured', models.BooleanField(default=False)),
                ('rights', models.JSONField(blank=True, default=dict)),
                ('audit', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Channel',
                'verbose_name_plural': 'Channels',
                'ordering': ['sort_order', 'id_slug'],
            },
        ),
    ]
