# Generated by Django 5.2.5 on 2025-08-29 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='youtube_channel_id',
            field=models.CharField(blank=True, help_text='Resolved UC... channel ID', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='channel',
            name='youtube_handle',
            field=models.CharField(blank=True, help_text='Channel handle like @ebstvWorldwide', max_length=128, null=True),
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('thumbnails', models.JSONField(blank=True, default=dict)),
                ('item_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=False, help_text='Mark playlists active to surface in apps')),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='channels.channel')),
            ],
            options={
                'verbose_name': 'Playlist',
                'verbose_name_plural': 'Playlists',
                'ordering': ['channel', 'title'],
            },
        ),
    ]
