# Generated by Django 5.2.5 on 2025-08-31 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0004_appversion_featureflag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('thumbnails', models.JSONField(blank=True, default=dict)),
                ('item_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=False, help_text='Mark playlists active to surface in apps')),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Playlist',
                'verbose_name_plural': 'Playlists',
                'ordering': ['channel', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(db_index=True, max_length=32)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('thumbnails', models.JSONField(blank=True, default=dict)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'ordering': ['playlist', 'position', 'video_id'],
            },
        ),
        migrations.AlterModelOptions(
            name='featureflag',
            options={},
        ),
        migrations.AddField(
            model_name='channel',
            name='youtube_channel_id',
            field=models.CharField(blank=True, help_text='Resolved UC... channel ID', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='channel',
            name='youtube_handle',
            field=models.CharField(blank=True, help_text='Channel handle like @ebstvWorldwide', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='appversion',
            name='features',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='appversion',
            name='platform',
            field=models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('web', 'Web')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='appversion',
            name='version',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='featureflag',
            name='enabled_for_staff',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='featureflag',
            name='min_android_version',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='featureflag',
            name='min_ios_version',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='featureflag',
            name='name',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='featureflag',
            name='rollout_percentage',
            field=models.IntegerField(default=100),
        ),
        migrations.AddIndex(
            model_name='appversion',
            index=models.Index(fields=['platform', '-released_at'], name='channels_ap_platfor_c2afbb_idx'),
        ),
        migrations.AddIndex(
            model_name='appversion',
            index=models.Index(fields=['platform', 'status'], name='channels_ap_platfor_b7d279_idx'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='channels.channel'),
        ),
        migrations.AddField(
            model_name='video',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='channels.channel'),
        ),
        migrations.AddField(
            model_name='video',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='channels.playlist'),
        ),
        migrations.AlterUniqueTogether(
            name='video',
            unique_together={('playlist', 'video_id')},
        ),
    ]
