# Generated by Django 5.2.5 on 2025-10-21 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0005_playlist_video_alter_featureflag_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('data', models.JSONField(blank=True, null=True)),
                ('target_type', models.CharField(choices=[('token', 'Token'), ('topic', 'Topic'), ('user', 'User')], default='token', max_length=10)),
                ('target_value', models.TextField(blank=True)),
                ('send_at', models.DateTimeField(help_text='UTC time to send')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['send_at'],
                'indexes': [models.Index(fields=['status', 'send_at'], name='channels_sc_status_7a88ad_idx'), models.Index(fields=['target_type'], name='channels_sc_target__290fc1_idx')],
            },
        ),
    ]
