# Generated by Django 5.2.5 on 2025-10-21 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0006_schedulednotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('first_login', 'First Login')], default='first_login', max_length=32)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('body', models.TextField(blank=True, default='')),
                ('tenant', models.CharField(blank=True, default='', help_text='Tenant slug (e.g., ontime). Leave blank for global', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['kind', 'tenant', 'is_active'], name='channels_an_kind_ac0dd9_idx'), models.Index(fields=['starts_at'], name='channels_an_starts__e0acc5_idx'), models.Index(fields=['ends_at'], name='channels_an_ends_at_7f3f6d_idx')],
            },
        ),
    ]
