# Generated by Django 5.2.5 on 2025-10-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0009_usernotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='is_shorts',
            field=models.BooleanField(db_index=True, default=False, help_text='Mark playlist as part of Shorts feed'),
        ),
    ]
