# Generated by Django 5.2.5 on 2025-10-28 19:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0010_playlist_is_shorts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant', models.CharField(db_index=True, default='ontime', max_length=64)),
                ('source_url', models.TextField(help_text='Original source URL or video identifier')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('downloading', 'Downloading'), ('transcoding', 'Transcoding'), ('uploading', 'Uploading'), ('ready', 'Ready'), ('retiring', 'Retiring'), ('deleted', 'Deleted'), ('failed', 'Failed')], db_index=True, default='queued', max_length=16)),
                ('error_message', models.TextField(blank=True, default='')),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('artifact_prefix', models.CharField(blank=True, default='', max_length=255)),
                ('ladder_profile', models.CharField(default='shorts_v1', max_length=64)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('reserved_bytes', models.BigIntegerField(default=0)),
                ('used_bytes', models.BigIntegerField(default=0)),
                ('hls_master_url', models.TextField(blank=True, default='')),
                ('content_class', models.CharField(choices=[('pinned', 'Pinned'), ('preferred', 'Preferred'), ('normal', 'Normal'), ('ephemeral', 'Ephemeral')], default='normal', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='short_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Short Ingestion Job',
                'verbose_name_plural': 'Short Ingestion Jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'status', '-created_at'], name='channels_sh_tenant_578646_idx')],
            },
        ),
    ]
