# Generated by Django 5.2.5 on 2025-10-30 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0011_shortjob'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='channels.shortjob')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='short_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['job', '-created_at'], name='channels_sh_job_id_3b3ff7_idx'), models.Index(fields=['user', '-created_at'], name='channels_sh_user_id_a5c06e_idx')],
            },
        ),
        migrations.CreateModel(
            name='ShortReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(choices=[(1, 'like'), (-1, 'dislike')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='channels.shortjob')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='short_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['job', 'user'], name='channels_sh_job_id_7f80bd_idx'), models.Index(fields=['job', 'value'], name='channels_sh_job_id_a4996b_idx')],
                'unique_together': {('job', 'user')},
            },
        ),
    ]
