# Generated by Django 5.2.5 on 2025-11-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0012_shortcomment_shortreaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='yt_last_item_published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playlist',
            name='yt_published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
