# Generated by Django 5.2.5 on 2025-08-30 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_socialaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='access_token_jti',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
