# Generated by Django 5.2.5 on 2025-08-31 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_access_token_jti'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='os_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='usersession',
            name='os_version',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
